// tex_doc_content.h - Documentation TEX pour TetraOS
#ifndef TEX_DOC_CONTENT_H
#define TEX_DOC_CONTENT_H

const char TEX_DOCUMENTATION[] = 
"===========================================\n"
"    DOCUMENTATION TEX - TetraExecutable    \n"
"===========================================\n"
"\n"
"TEX est le systeme d'execution de scripts de TetraOS.\n"
"Les fichiers .tex permettent d'ecrire des programmes\n"
"executables directement dans l'OS.\n"
"\n"
"Syntaxe proche de JavaScript/Python.\n"
"\n"
"--- UTILISATION BASIQUE ---\n"
"\n"
"1. Creer un fichier .tex :\n"
"   touch monscript.tex\n"
"\n"
"2. Editer le fichier :\n"
"   edit monscript.tex\n"
"\n"
"3. Executer le script :\n"
"   tex monscript.tex\n"
"\n"
"--- VARIABLES ---\n"
"\n"
"Declarer une variable :\n"
"  var nom = valeur\n"
"  var age = 25\n"
"  var nom = \"Alice\"\n"
"\n"
"Declarer une constante :\n"
"  const PI = 3.14\n"
"  const MAX = 100\n"
"\n"
"Expressions arithmetiques :\n"
"  var x = 5 + 3\n"
"  var y = x * 2\n"
"  var z = (x + y) / 2\n"
"\n"
"--- AFFICHAGE ---\n"
"\n"
"Afficher du texte :\n"
"  io.print(\"Hello\")\n"
"  io.println(\"Hello\")    // avec retour ligne\n"
"\n"
"Afficher des variables :\n"
"  io.print(age)\n"
"  io.println(\"Age: \" + age)\n"
"\n"
"Concatenation :\n"
"  io.println(\"Bonjour \" + nom)\n"
"\n"
"--- SAISIE UTILISATEUR ---\n"
"\n"
"Demander une entree :\n"
"  io.input(\"Votre nom: \", nom)\n"
"  io.input(\"Votre age: \", age)\n"
"\n"
"--- CONDITIONS ---\n"
"\n"
"Structure if :\n"
"  if condition {\n"
"    // instructions\n"
"  }\n"
"\n"
"Operateurs de comparaison :\n"
"  ==  (egal)\n"
"  !=  (different)\n"
"  <   (inferieur)\n"
"  >   (superieur)\n"
"  <=  (inferieur ou egal)\n"
"  >=  (superieur ou egal)\n"
"\n"
"Exemple :\n"
"  if age >= 18 {\n"
"    io.println(\"Majeur\")\n"
"  }\n"
"\n"
"  if x == 0 {\n"
"    io.println(\"Zero\")\n"
"  }\n"
"\n"
"--- SYSTEME DE FICHIERS ---\n"
"\n"
"Ecrire dans un fichier :\n"
"  fs.write(\"data.txt\", \"contenu\")\n"
"  fs.write(\"data.txt\", text)\n"
"\n"
"Lire un fichier :\n"
"  fs.read(\"data.txt\", contenu)\n"
"\n"
"Verifier si un fichier existe :\n"
"  fs.exists(\"data.txt\", existe)\n"
"  if existe == 1 {\n"
"    io.println(\"Fichier trouve\")\n"
"  }\n"
"\n"
"Supprimer un fichier :\n"
"  fs.delete(\"data.txt\")\n"
"\n"
"--- COMMANDES SYSTEME ---\n"
"\n"
"Effacer l'ecran :\n"
"  clear\n"
"  // ou\n"
"  clear()\n"
"\n"
"Quitter le script :\n"
"  exit\n"
"  // ou\n"
"  exit()\n"
"\n"
"--- EXEMPLE COMPLET ---\n"
"\n"
"// Programme de compteur\n"
"clear\n"
"io.println(\"=== Compteur ===\")\n"
"io.input(\"Entrez max: \", max)\n"
"\n"
"var i = 0\n"
"if i < max {\n"
"  io.print(\"Comptage: \")\n"
"  io.println(i)\n"
"  i = i + 1\n"
"}\n"
"\n"
"io.println(\"Termine!\")\n"
"exit\n"
"\n"
"--- EXEMPLE : CALCULATRICE ---\n"
"\n"
"clear\n"
"io.println(\"Calculatrice\")\n"
"io.input(\"Nombre 1: \", a)\n"
"io.input(\"Nombre 2: \", b)\n"
"\n"
"var somme = a + b\n"
"var produit = a * b\n"
"\n"
"io.print(\"Somme: \")\n"
"io.println(somme)\n"
"io.print(\"Produit: \")\n"
"io.println(produit)\n"
"\n"
"--- EXEMPLE : FICHIERS ---\n"
"\n"
"// Sauvegarder des donnees\n"
"io.input(\"Votre nom: \", nom)\n"
"fs.write(\"save.txt\", nom)\n"
"io.println(\"Sauvegarde!\")\n"
"\n"
"// Charger des donnees\n"
"fs.exists(\"save.txt\", found)\n"
"if found == 1 {\n"
"  fs.read(\"save.txt\", data)\n"
"  io.print(\"Charge: \")\n"
"  io.println(data)\n"
"}\n"
"\n"
"--- LIMITATIONS ---\n"
"\n"
"- Maximum 64 variables\n"
"- Maximum 256 lignes par script\n"
"- Pas de boucles for/while (utilisez if)\n"
"- Pas de fonctions utilisateur\n"
"- Arithmetique entiere seulement\n"
"\n"
"===========================================\n"
"Pour plus d'aide : tapez 'help'\n"
"===========================================\n";

#endif // TEX_DOC_CONTENT_H